GET http://localhost:3031/
###
GET http://localhost:3031/toto/
###
GET http://localhost:3031/add_task/super_tache/
###
GET http://localhost:3031/get_all_tasks/
###
PATCH http://localhost:3031/update_task/2/true/
###
DELETE http://localhost:3031/remove_task/3/
###
DELETE http://localhost:3031/remove_all_tasks/3/